name: GBAWatch
options:
  deploymentTarget:
    watchOS: "10.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Automatic
targets:
  WatchExtension:
    type: watchkit2-extension
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - path: GBAWatch
        excludes:
          - Info.plist
    info:
      path: GBAWatch/Info.plist
      properties:
        CFBundleDisplayName: GBA Watch
        NSExtension:
          NSExtensionAttributes:
            WKAppBundleIdentifier: com.beich.GBAWatch.ios.watchkitapp
          NSExtensionPointIdentifier: com.apple.watchkit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.beich.GBAWatch.ios.watchkitapp.watchkitextension
        TARGETED_DEVICE_FAMILY: "4"
  WatchApp:
    type: application.watchapp2
    platform: watchOS
    deploymentTarget: "10.0"
    sources: []
    dependencies:
      - target: WatchExtension
    info:
      path: GBAWatchApp/Info.plist
      properties:
        CFBundleDisplayName: GBA Watch
        WKWatchKitApp: true
        WKCompanionAppBundleIdentifier: com.beich.GBAWatch.ios
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.beich.GBAWatch.ios.watchkitapp
        TARGETED_DEVICE_FAMILY: "4"
  GBACompanion:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: GBACompanion
        excludes:
          - Info.plist
    dependencies:
      - target: WatchApp
        embed: true
    info:
      path: GBACompanion/Info.plist
      properties:
        CFBundleDisplayName: GBA Watch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.beich.GBAWatch.ios
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  GBAWatch:
    build:
      targets:
        WatchApp: all
        WatchExtension: all
    run:
      config: Debug
  GBACompanion:
    build:
      targets:
        GBACompanion: all
    run:
      config: Debug
